CREATE DATABASE  sphchatdb;
use sphchatdb;
drop table sphchatdb.sph_chatbot;
CREATE TABLE `sph_chatbot` (
 `chatbot_id` int(11) NOT NULL AUTO_INCREMENT,
 `first_name` varchar(100) NOT NULL,
 `last_name` varchar(100) NOT NULL,
 `phone_number` varchar(100) NOT NULL,
 `email` varchar(100) NOT NULL,
`bill_to_address_line1` varchar(100) NOT NULL,
`bill_to_address_city` varchar(100) NOT NULL,
`bill_to_address_state` varchar(100) NOT NULL,
`bill_to_address_postal_code` varchar(100) NOT NULL,
`bill_to_country` varchar(100) NOT NULL,
`price` varchar(100) DEFAULT NULL,
`days` varchar(100) DEFAULT NULL,
`sub_total` varchar(100) DEFAULT NULL,
`gst` varchar(100) DEFAULT NULL,
`total` varchar(100) DEFAULT NULL,
 `create_timestamp` datetime NOT NULL,
 `publication` varchar(100) DEFAULT NULL,
 `ad_type` varchar(100) DEFAULT NULL,
 `ad_nature` varchar(100) DEFAULT NULL,
 `start_date` date DEFAULT NULL,
 `end_date` date DEFAULT NULL,
 `ad_vehicle_image_name` varchar(100) DEFAULT NULL,
 `ad_property_image_name` varchar(100) DEFAULT NULL,
 `ad_vehicle_qr_code_name` varchar(100) DEFAULT NULL,
 `ad_property_qr_code_name` varchar(100) DEFAULT NULL,
 `totat_paid` varchar(100) DEFAULT NULL,
 `property_bedrooms` varchar(100) DEFAULT NULL,
 `vehicle_reg_date` varchar(100) DEFAULT NULL,
 `is_payment_success` tinyint(1) DEFAULT 0,
 `business_lead_informed_time` tinyint(1) DEFAULT 0,
 `has_property_qr_code` tinyint(1) DEFAULT 0,
 `has_vehicle_qr_code` tinyint(1) DEFAULT 0,
 `advertisement_text` varchar(100) DEFAULT NULL,
 `vehicle_price` varchar(100) DEFAULT NULL,
 `property_price` varchar(100) DEFAULT NULL,
 `service_nature` varchar(100) DEFAULT NULL,
 `ad_service_image_name` varchar(100) DEFAULT NULL,
 `ad_service_qr_image_name` varchar(100) DEFAULT NULL,
 `service_charge` varchar(100) DEFAULT NULL,
 `property_area` varchar(100) DEFAULT NULL,
 `is_active` tinyint(1) DEFAULT 0,
 `choosen_worng_language` tinyint(1) DEFAULT 0,
 `vehicle_brand` varchar(100) DEFAULT NULL,
 `vehicle_mileage` varchar(100) DEFAULT NULL,
 `property_type` varchar(100) DEFAULT NULL,
`token` varchar(100) NOT NULL,
`validity` datetime NOT NULL,
 PRIMARY KEY (`chatbot_id`)
) 